@startuml

interface Curator {
	+ Collect(): error
	+ Reserch(): error
	+ Save(): error
	+ Show(): error
}

class BaseCurator {
    + Target: string
    - data: []interface{}
	+ Collect(): error
	+ Reserch(): error
	+ Save(): error
	+ Show(): error
}

interface Authenticator{
	+ Auth(): error
}

class ApiCurator {
	+ ClientID: string
	+ ClientSecret: string
	+ Auth(): error
}

class GurunaviCurator {
}

class SpotifyCurator {
}

class TwitterCurator {
	+ Tweets []Tweet
}

class ScrapeCurator {
}

class TabelogCurator {
}

class Tweet {
    - id : int
    - text : string
	+ Text(): string
}

Curator <|.. BaseCurator
note on link
実現関係
end note

BaseCurator <|-- ApiCurator
note on link
継承
end note

BaseCurator <|-- ScrapeCurator
ScrapeCurator <|-- TabelogCurator


Authenticator <|.. ApiCurator

ApiCurator <|-- GurunaviCurator
ApiCurator <|-- SpotifyCurator
ApiCurator <|-- TwitterCurator
TwitterCurator *--> Tweet
note on link
コンポジション
end note

@enduml